from __future__ import annotations

import os
from typing import Any

from PySide6.QtCore import Qt, QSize
from PySide6.QtGui import QPixmap
from PySide6.QtWidgets import (
    QCheckBox,
    QComboBox,
    QFormLayout,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QListWidget,
    QListWidgetItem,
    QSlider,
    QStackedWidget,
    QTextEdit,
    QVBoxLayout,
    QWidget,
)

from ...core.brand import APP_DISPLAY_NAME, APP_TAGLINE, ICON_PNG
from ...core.brand_assets import ensure_logo_on_desktop
from ...core.paths import ensure_dirs
from ...core.registry import CAPABILITIES
from ...core.runbooks import RUNBOOKS
from ...core.utils import resource_path
from ...core.version import APP_VERSION
from ...core.logging_setup import log_path, logs_dir
from ..theme import available_palette_labels, resolve_density_tokens
from ..widgets import Card, DrawerCard, SoftButton
from .common import PageScroll, build_page_header


class SettingsPage(PageScroll):
    def __init__(self, services: Any) -> None:
        super().__init__(page_id="settings", object_name="PageSettings")
        self.services = services
        self._build_ui()

    def _build_ui(self) -> None:
        w = self.services
        layout = QVBoxLayout(self.content)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(10)
        layout.addWidget(
            build_page_header(
                "Settings",
                "Policy, privacy, appearance, and support settings.",
                help_text="Each setting includes plain-English impact; details stay collapsed until needed.",
                on_help=w._show_page_help,
            )
        )

        toolbar = Card("Settings Tools", "Search, reset defaults, or export current settings.")
        tools_row = QWidget()
        tools_row_l = QVBoxLayout(tools_row)
        tools_row_l.setContentsMargins(0, 0, 0, 0)
        tools_row_l.setSpacing(6)
        tools_row_top = QHBoxLayout()
        tools_row_top.setContentsMargins(0, 0, 0, 0)
        tools_row_top.setSpacing(8)
        tools_row_bottom = QHBoxLayout()
        tools_row_bottom.setContentsMargins(0, 0, 0, 0)
        tools_row_bottom.setSpacing(8)
        w.settings_search = QLineEdit()
        w.settings_search.setObjectName("SearchInput")
        w.settings_search.setPlaceholderText("Search settings")
        w.settings_search.textChanged.connect(w._filter_settings_nav)
        b_reset = SoftButton("Reset Defaults")
        w.s_export_btn = SoftButton("Export Settings JSON")
        b_help = SoftButton("Help Center")
        b_reset.clicked.connect(w._reset_settings_defaults)
        w.s_export_btn.clicked.connect(w._export_settings_json)
        b_help.clicked.connect(lambda: w._show_page_help("Settings", "Safety, privacy, and rollback guidance."))
        tools_row_top.addWidget(w.settings_search, 1)
        tools_row_bottom.addWidget(b_reset, 0)
        tools_row_bottom.addWidget(w.s_export_btn, 0)
        tools_row_bottom.addWidget(b_help, 0)
        tools_row_bottom.addStretch(1)
        tools_row_l.addLayout(tools_row_top)
        tools_row_l.addLayout(tools_row_bottom)
        toolbar.body_layout().addWidget(tools_row)
        layout.addWidget(toolbar)

        shell = QHBoxLayout()
        shell.setContentsMargins(0, 0, 0, 0)
        shell.setSpacing(10)
        w.settings_nav = QListWidget()
        w.settings_nav.setObjectName("SettingsNav")
        w.settings_nav.setMinimumWidth(200)
        w.settings_nav.setMaximumWidth(280)
        settings_row_height = resolve_density_tokens(w.settings_state.density).nav_item_height
        settings_sections = ("Safety", "Privacy", "Privacy & Safety", "Appearance", "Advanced", "About", "Feedback")
        for name in settings_sections:
            item = QListWidgetItem(name)
            item.setData(Qt.UserRole, name)
            item.setSizeHint(QSize(0, settings_row_height))
            w.settings_nav.addItem(item)
            w.settings_nav.setItemWidget(item, w._settings_nav_item_widget(name))
        w.settings_stack = QStackedWidget()
        w.settings_nav.currentRowChanged.connect(lambda idx: w.settings_stack.setCurrentIndex(max(idx, 0)))
        w.settings_nav.currentRowChanged.connect(w._on_settings_section_changed)
        shell.addWidget(w.settings_nav, 0)

        p_safety = QWidget()
        psl = QVBoxLayout(p_safety)
        psl.setContentsMargins(0, 0, 0, 0)
        psl.setSpacing(10)
        c_safe = Card("Safety", "Safe/Admin/Advanced levels and rollback guidance.")
        w.s_safe = QCheckBox("Safe-only mode")
        w.s_admin = QCheckBox("Enable Admin Tools")
        w.s_admin_hint = w._setting_hint("Enable admin tools only when you need elevated actions.")
        w.s_safe_hint = w._setting_hint("Default safety guardrail. Shows only low-risk actions.")
        w.s_adv = QCheckBox("Show advanced tools")
        w.s_diag = QCheckBox("Diagnostic mode")
        for x in (w.s_safe, w.s_admin, w.s_adv, w.s_diag):
            x.stateChanged.connect(w.save_settings_from_ui)
        c_safe.body_layout().addWidget(w.s_safe)
        c_safe.body_layout().addWidget(w.s_safe_hint)
        c_safe.body_layout().addWidget(w.s_admin)
        c_safe.body_layout().addWidget(w.s_admin_hint)
        c_safe.body_layout().addWidget(w.s_adv)
        c_safe.body_layout().addWidget(w._setting_hint("Shows advanced operations intended for experienced users."))
        c_safe.body_layout().addWidget(w.s_diag)
        c_safe.body_layout().addWidget(w._setting_hint("Adds extra diagnostic visibility in select flows."))
        c_safe.body_layout().addWidget(QLabel("Definitions"))
        c_safe.body_layout().addWidget(w._setting_hint("Safe: low-risk checks and guided actions."))
        c_safe.body_layout().addWidget(w._setting_hint("Admin: elevated commands with explicit confirmation."))
        c_safe.body_layout().addWidget(w._setting_hint("Advanced: expert workflows that may require manual verification."))
        c_safe.body_layout().addWidget(QLabel("Restore and rollback"))
        c_safe.body_layout().addWidget(w._setting_hint("Use rollback notes in Fixes detail before running changes."))
        c_safe.body_layout().addWidget(w._setting_hint("If a reboot is requested, rerun diagnostics after restart to confirm outcomes."))
        c_safe.body_layout().addWidget(w._setting_details("Advanced/admin tools may require elevation, reboots, or manual rollback."))
        psl.addWidget(c_safe)
        psl.addStretch(1)

        p_privacy = QWidget()
        ppl = QVBoxLayout(p_privacy)
        ppl.setContentsMargins(0, 0, 0, 0)
        ppl.setSpacing(10)
        c_priv = Card("Privacy", "Local-first data handling and share-safe controls.")
        w.s_share = QCheckBox("Enable share-safe by default")
        w.s_ip = QCheckBox("Mask IP by default")
        w.s_share.stateChanged.connect(w.save_settings_from_ui)
        w.s_ip.stateChanged.connect(w.save_settings_from_ui)
        c_priv.body_layout().addWidget(w.s_share)
        c_priv.body_layout().addWidget(w._setting_hint("Automatically masks user/device identifiers when copying or exporting."))
        c_priv.body_layout().addWidget(w.s_ip)
        c_priv.body_layout().addWidget(w._setting_hint("Masks private/public IP tokens in summaries and exported text evidence."))
        c_priv.body_layout().addWidget(QLabel("What Fix Fox stores locally"))
        c_priv.body_layout().addWidget(w._setting_hint("Sessions, findings, selected actions, evidence file references, and optional logs."))
        c_priv.body_layout().addWidget(QLabel("Storage location"))
        c_priv.body_layout().addWidget(w._setting_hint(r"%LOCALAPPDATA%\\FixFox\\... (app data, sessions, exports, logs)."))
        c_priv.body_layout().addWidget(QLabel("What is not collected"))
        c_priv.body_layout().addWidget(w._setting_hint("Passwords, browser history content, clipboard history, and telemetry data."))
        c_priv.body_layout().addWidget(w._setting_details("Masking applies to UI copy actions, Tool Runner copy/save, and export pack generation."))
        ppl.addWidget(c_priv)
        ppl.addStretch(1)

        p_priv_safety = QWidget()
        pps = QVBoxLayout(p_priv_safety)
        pps.setContentsMargins(0, 0, 0, 0)
        pps.setSpacing(10)
        local_paths = ensure_dirs()
        c_truth = Card("Privacy & Safety", "Everything in Fix Fox runs locally on this machine.")
        c_truth.body_layout().addWidget(QLabel("No telemetry: Fix Fox does not send diagnostics, sessions, or logs to external services."))
        c_truth.body_layout().addWidget(QLabel("Session storage: local JSON and sqlite state for faster history/search."))
        c_truth.body_layout().addWidget(QLabel("Exports: generated only when you explicitly run Reports -> Generate Export."))
        c_truth.body_layout().addWidget(QLabel(f"Sessions path: {local_paths['sessions']}"))
        c_truth.body_layout().addWidget(QLabel(f"Logs path: {local_paths['logs']}"))
        c_truth.body_layout().addWidget(QLabel(f"Exports path: {local_paths['exports']}"))
        c_truth.body_layout().addWidget(w._setting_hint("Safe-only limits actions to low-risk defaults. Admin and Advanced show elevated/experts-only actions."))
        pps.addWidget(c_truth)
        pps.addStretch(1)

        p_appearance = QWidget()
        pal = QVBoxLayout(p_appearance)
        pal.setContentsMargins(0, 0, 0, 0)
        pal.setSpacing(10)
        c_look = Card("Appearance", "Theme applies live across the whole app.")
        w.s_panel = QCheckBox("Keep concierge panel open")
        w.s_weekly = QCheckBox("Enable weekly check reminder")
        w.s_nav_compact = QCheckBox("Compact navigation rail")
        w.s_drawer_pin = QCheckBox("Pin details drawer")
        w.s_panel.stateChanged.connect(w.save_settings_from_ui)
        w.s_weekly.stateChanged.connect(w.save_settings_from_ui)
        w.s_nav_compact.stateChanged.connect(w.save_settings_from_ui)
        w.s_drawer_pin.stateChanged.connect(w.save_settings_from_ui)
        w.s_palette = QComboBox()
        w.s_palette.addItems(list(available_palette_labels()))
        w.s_palette.currentTextChanged.connect(w.save_settings_from_ui)
        w.s_mode = QComboBox()
        w.s_mode.addItems(["dark", "light"])
        w.s_mode.currentTextChanged.connect(w.save_settings_from_ui)
        w.s_density = QComboBox()
        w.s_density.addItems(["comfortable", "compact"])
        w.s_density.currentTextChanged.connect(w.save_settings_from_ui)
        w.s_ui_mode = QComboBox()
        w.s_ui_mode.addItems(["basic", "pro"])
        w.s_ui_mode.currentTextChanged.connect(w.set_ui_mode)
        c_look.body_layout().addWidget(w.s_panel)
        w.s_panel_hint = w._setting_hint("Keeps the right concierge panel expanded when window width allows.")
        c_look.body_layout().addWidget(w.s_panel_hint)
        c_look.body_layout().addWidget(w.s_weekly)
        c_look.body_layout().addWidget(w._setting_hint("Shows a weekly reminder card on Home."))
        c_look.body_layout().addWidget(w.s_nav_compact)
        c_look.body_layout().addWidget(w._setting_hint("Collapses main navigation to icon rail only."))
        c_look.body_layout().addWidget(w.s_drawer_pin)
        c_look.body_layout().addWidget(w._setting_hint("Keeps details drawer open at smaller widths when enabled."))
        c_look.body_layout().addWidget(QLabel("UI Mode"))
        c_look.body_layout().addWidget(w.s_ui_mode)
        c_look.body_layout().addWidget(w._setting_hint("Basic focuses on guided safe flows. Pro exposes full tool/runbook directories."))
        c_look.body_layout().addWidget(QLabel("Palette"))
        c_look.body_layout().addWidget(w.s_palette)
        c_look.body_layout().addWidget(w._setting_hint("Pick from three real palettes: Fix Fox, Graphite, and High Contrast."))
        c_look.body_layout().addWidget(QLabel("Mode"))
        c_look.body_layout().addWidget(w.s_mode)
        c_look.body_layout().addWidget(w._setting_hint("Switch between dark and light theme mode."))
        c_look.body_layout().addWidget(QLabel("Density"))
        c_look.body_layout().addWidget(w.s_density)
        c_look.body_layout().addWidget(w._setting_hint("Comfortable increases spacing; compact fits more rows on screen."))
        c_look.body_layout().addWidget(QLabel("UI Scale"))
        w.s_ui_scale_value = QLabel("100%")
        w.s_ui_scale = QSlider(Qt.Horizontal)
        w.s_ui_scale.setRange(90, 125)
        w.s_ui_scale.setSingleStep(1)
        w.s_ui_scale.setPageStep(5)
        w.s_ui_scale.valueChanged.connect(w._on_ui_scale_value_changed)
        w.s_ui_scale.sliderReleased.connect(w._persist_ui_scale_setting)
        c_look.body_layout().addWidget(w.s_ui_scale_value)
        c_look.body_layout().addWidget(w.s_ui_scale)
        c_look.body_layout().addWidget(w._setting_hint("Scales typography and control density from 90% to 125%."))
        c_look.body_layout().addWidget(w._setting_details("Theme, mode, and density apply live at QApplication scope across all pages."))
        preview = Card("Preview", "Changes are applied immediately. Use this panel to compare density and contrast.")
        pal.addWidget(c_look)
        pal.addWidget(preview)
        pal.addStretch(1)

        p_advanced = QWidget()
        pdl = QVBoxLayout(p_advanced)
        pdl.setContentsMargins(0, 0, 0, 0)
        pdl.setSpacing(10)
        c_adv = Card("Advanced", "Operational paths and logs.")
        b_open = SoftButton("Open Logs Folder")
        b_open.clicked.connect(lambda: os.startfile(str(logs_dir())) if os.name == "nt" else None)
        b_copy = SoftButton("Copy Log Path")
        b_copy.clicked.connect(lambda: w._copy_text(str(log_path())))
        b_data = SoftButton("Open Data Folder")
        b_data.clicked.connect(lambda: os.startfile(str(ensure_dirs()["base"])) if os.name == "nt" else None)
        b_diag = SoftButton("Export Diagnostics")
        b_diag.clicked.connect(w._collect_core_evidence)
        b_logo = SoftButton("Create Desktop Logo")
        b_logo.clicked.connect(lambda: w.create_desktop_logo(force=False))
        b_logo_recreate = SoftButton("Recreate Desktop Logo")
        b_logo_recreate.clicked.connect(lambda: w.create_desktop_logo(force=True))
        b_rebuild_db = SoftButton("Rebuild Database Index")
        b_rebuild_db.clicked.connect(w._rebuild_database_index)
        b_vacuum_db = SoftButton("Vacuum Database")
        b_vacuum_db.clicked.connect(w._vacuum_database_now)
        b_clear_file_index = SoftButton("Clear File Index")
        b_clear_file_index.clicked.connect(w._clear_file_index_now)
        w.db_info_label = QLabel("Database: loading...")
        w.db_info_label.setWordWrap(True)
        c_adv.body_layout().addWidget(b_open)
        c_adv.body_layout().addWidget(w._setting_hint("Open application log directory in File Explorer."))
        c_adv.body_layout().addWidget(b_copy)
        c_adv.body_layout().addWidget(w._setting_hint("Copy absolute path to the active log file."))
        c_adv.body_layout().addWidget(b_data)
        c_adv.body_layout().addWidget(w._setting_hint("Open app data root for sessions, state, and exports."))
        c_adv.body_layout().addWidget(w.db_info_label)
        c_adv.body_layout().addWidget(b_rebuild_db)
        c_adv.body_layout().addWidget(w._setting_hint("Rebuilds SQLite index from session JSON files (safe/idempotent)."))
        c_adv.body_layout().addWidget(b_vacuum_db)
        c_adv.body_layout().addWidget(w._setting_hint("Compacts SQLite database and can improve read/write performance."))
        c_adv.body_layout().addWidget(b_clear_file_index)
        c_adv.body_layout().addWidget(w._setting_hint("Clears file index rows without deleting session data."))
        c_adv.body_layout().addWidget(b_diag)
        c_adv.body_layout().addWidget(w._setting_hint("Runs core evidence collection and attaches output for export."))
        c_adv.body_layout().addWidget(b_logo)
        c_adv.body_layout().addWidget(w._setting_hint("Creates FixFoxLogo.png on your Desktop for support docs/screenshots."))
        c_adv.body_layout().addWidget(b_logo_recreate)
        pdl.addWidget(c_adv)
        pdl.addStretch(1)

        p_about = QWidget()
        pol = QVBoxLayout(p_about)
        pol.setContentsMargins(0, 0, 0, 0)
        pol.setSpacing(10)
        c_about = Card("About", f"Version {APP_VERSION}")
        about_header = QWidget()
        about_header_l = QHBoxLayout(about_header)
        about_header_l.setContentsMargins(0, 0, 0, 0)
        about_header_l.setSpacing(10)
        icon = QLabel()
        pix = QPixmap(resource_path(ICON_PNG))
        if not pix.isNull():
            icon.setPixmap(pix.scaled(40, 40, Qt.KeepAspectRatio, Qt.SmoothTransformation))
        title_block = QVBoxLayout()
        title_block.setContentsMargins(0, 0, 0, 0)
        title_block.setSpacing(2)
        title_block.addWidget(QLabel(APP_DISPLAY_NAME))
        title_block.addWidget(w._setting_hint(APP_TAGLINE))
        about_header_l.addWidget(icon)
        about_header_l.addLayout(title_block, 1)
        c_about.body_layout().addWidget(about_header)
        c_about.body_layout().addWidget(QLabel("Runs locally. No cloud uploads or telemetry."))
        c_about.body_layout().addWidget(QLabel("Plain English: this app runs diagnostics, fixes, runbooks, and exports locally."))
        c_about.body_layout().addWidget(QLabel("Privacy summary: session data, evidence, and logs stay on this device unless you export/share manually."))
        c_about.body_layout().addWidget(QLabel("Safety summary: Safe = low-risk checks, Admin = elevated actions, Advanced = expert workflows."))
        c_about.body_layout().addWidget(QLabel("Optional online actions are explicitly labeled (for example, Microsoft Get Help)."))
        c_about.body_layout().addWidget(QLabel(f"Data folder: {ensure_dirs()['base']}"))
        c_about.body_layout().addWidget(QLabel(f"Logs folder: {logs_dir()}"))
        c_about.body_layout().addWidget(QLabel(f"Capabilities: {len(CAPABILITIES)}"))
        c_about.body_layout().addWidget(QLabel(f"Runbooks: {len(RUNBOOKS)}"))
        about_privacy = SoftButton("Open Privacy Page")
        about_privacy.clicked.connect(lambda: w._open_settings_section("Privacy"))
        about_safety = SoftButton("Open Safety Page")
        about_safety.clicked.connect(lambda: w._open_settings_section("Safety"))
        c_about.body_layout().addWidget(about_privacy)
        c_about.body_layout().addWidget(about_safety)
        about_logo = SoftButton("Create Desktop Logo")
        about_logo.clicked.connect(lambda: ensure_logo_on_desktop(overwrite=False))
        c_about.body_layout().addWidget(about_logo)
        pol.addWidget(c_about)
        pol.addStretch(1)

        p_feedback = QWidget()
        pfl = QVBoxLayout(p_feedback)
        pfl.setContentsMargins(0, 0, 0, 0)
        pfl.setSpacing(10)
        c_fb = Card("Local Feedback", "Saved as JSON locally; no network calls.")
        form = QWidget()
        fl = QFormLayout(form)
        w.fb_name = QLineEdit()
        w.fb_mail = QLineEdit()
        w.fb_cat = QComboBox()
        w.fb_cat.addItems(["bug", "ui", "feature", "other"])
        w.fb_msg = QTextEdit()
        w.fb_msg.setMinimumHeight(120)
        fl.addRow("Name", w.fb_name)
        fl.addRow("Email", w.fb_mail)
        fl.addRow("Category", w.fb_cat)
        fl.addRow("Message", w.fb_msg)
        b_save = SoftButton("Save Feedback")
        b_save.clicked.connect(w.save_feedback_form)
        c_fb.body_layout().addWidget(form)
        c_fb.body_layout().addWidget(b_save)
        pfl.addWidget(c_fb)
        pfl.addStretch(1)

        for page in (p_safety, p_privacy, p_priv_safety, p_appearance, p_advanced, p_about, p_feedback):
            w.settings_stack.addWidget(page)
        shell.addWidget(w.settings_stack, 1)
        layout.addLayout(shell, 1)
